
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

# if running bash
if [ -n "$BASH_VERSION" ]; then
  # include .bashrc if it exsists
  if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
  fi
fi
# add $HOME/bin to the path if it exists
if [ -d "$HOME/bin" ]; then
  PATH="$HOME/bin:$PATH"
fi

# The next line updates PATH for the Google Cloud SDK.
source '/Users/ryan/google-cloud-sdk/path.bash.inc'

# The next line enables bash completion for gcloud.
source '/Users/ryan/google-cloud-sdk/completion.bash.inc'
  

